### ISSUE TITLE
Just a bunch of errors

### ISSUE THREAD

**Issue by Techno3600** [WheezyGold7931/Mineplex-Core#14]
Hey Guys,
I was trying to use this and it did not work, I downloaded all the plugins and stuff with your links.

https://pastebin.com/E23Qi5D1

**Comment by WheezyGold7931** [comment]
Hello,
There seems to be no errors regarding MCR itself and more add-on based errors. These errors are basically standard these days. If you are getting skript parser errors please submit them in a new issue 😜
