### ISSUE TITLE
Reply to "Just a bunch or errors".

### ISSUE THREAD

**Issue by Techno3600** [WheezyGold7931/Mineplex-Core#15]
Wait,

I still need to know why I am my able to do any of the commands. It doesn't seem it work, even after I enabled Skript.

Sorry for opening anther ticket, for some reason I was not able to reply to the first one.

**Comment by WheezyGold7931** [comment]
Can I get a copy of your /plugins /ver Skript and /icanhasbukkit

**Comment by Techno3600** [comment]
I do not have any other plugins, I am using a test server. And I have whatever version included in the dependencies link. I am not exactly sure what /icanhasbukkit is, I use BuildTools.

**Comment by Nathan100YT** [comment]
Do you have a copy(screenshot) of your /plugins /ver Skript and /icanhasbukkit?

**Comment by Torksi** [comment]
You must use Spigot 1.8.8

**Comment by WheezyGold7931** [comment]
Closed due to inactivity

**Comment by Techno3600** [comment]
Here it is:
https://pastebin.com/E23Qi5D1
http://imgur.com/a/aw8bM

Why doesn't it work?

Thanks
