### ISSUE TITLE
MySQL won't connect

### ISSUE THREAD

**Issue by Camnooten** [WheezyGold7931/Mineplex-Core#25]
# Issue Template
MySQL won't connect

## Bug Description
When I start the skript, it won't connect to MySQL. I am using PhpMyAdmin

## Screenshot of /plugins
http://i.imgur.com/Sb4uPqv.jpg

## Screenshot of /ver Skript
http://i.imgur.com/MawjT1b.jpg

## Screenshot of /icanhasbukkit
http://i.imgur.com/h5XZUIq.jpg

## Bullet Points of how to get this bug
i dont know what i'm doing wrong
```
#!  If you want to use MySQL features edit the details below
script options:
    $ db url jdbc:mysql://<HOST>:3306/<DATABASE>
    $ db username root
    $ db password cameron4
```

**Comment by Camnooten** [comment]
Fixed.

**Comment by Torksi** [comment]
Locking this.
