### ISSUE TITLE
Line 197 Issue

### ISSUE THREAD

**Issue by PixelMaster3D** [WheezyGold7931/Mineplex-Core#3]
In line 197, you have a typo on a color error on this:

`			send "&f/mineplex-core useScoreboard (true/false) 7eToggles if you want to use Mineplex Core's Scoreboard!"`

When it should be this:

`			send "&f/mineplex-core useScoreboard (true/false) &eToggles if you want to use Mineplex Core's Scoreboard!"`

That's all I see for now, thanks!

**Comment by WheezyGold7931** [comment]
Being fixed in 2.2

**Comment by WheezyGold7931** [comment]
Done!
