### ISSUE TITLE
[Request] Mineplex Communities for v2.2 Update

### ISSUE THREAD

**Issue by PixelMaster3D** [WheezyGold7931/Mineplex-Core#4]
Hey, this isn't really an issue, just a request. But can you Mineplex Communities to the script, that would be great.

YouTube Source:

https://youtu.be/1RI2ZjYgJ5I

**Comment by WheezyGold7931** [comment]
I plan to add this ;)

**Comment by WheezyGold7931** [comment]
Planned, Issue Dismissed
