### ISSUE TITLE
Meta-Lore Enchantment in /give Comnand not Working

### ISSUE THREAD

**Issue by Techno3600** [WheezyGold7931/Mineplex-Core#42]
Hello,

Before I submit an actual bug report I was just wondering how to put the meta-lore on items with the /give command. I want to make sure that it’s not just me doing the command syntax wrong.
Right now I’m doing “/give all diamond_leggings 1 protection:3” and it gives me the leggings but not with the enchantment.

Thanks
Techno

**Comment by xLengoBug5** [comment]
Enchantments have not been added yet to /give.

**Comment by Techno3600** [comment]
Okay, thanks!

**Comment by xMRENDERMAN** [comment]
~Bump 
@Techno3600 I have just made a pull request containing code for the /give enchantments to work. They should be added in 3.0.

**Comment by Techno3600** [comment]
Your a god, thanks so much!!!!!!
